# Generated by Django 6.0.1 on 2026-02-04 13:39

import parts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[parts.validators.validate_part_price]),
        ),
    ]
