# Generated by Django 6.0.1 on 2026-02-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
    ]
