# Generated by Django 6.0.1 on 2026-04-04 18:14

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    garage_owner_group, _ = Group.objects.get_or_create(name='Garage Owner')
    mechanic_group, _ = Group.objects.get_or_create(name='Mechanic')


    garage_owner_permissions = Permission.objects.filter(
        codename__in=[
            'add_car', 'change_car', 'delete_car', 'view_car',
            'add_part', 'change_part', 'delete_part', 'view_part',
            'add_manufacturer', 'change_manufacturer', 'view_manufacturer',
            'add_category', 'change_category', 'view_category',
        ]
    )
    garage_owner_group.permissions.set(garage_owner_permissions)


    mechanic_permissions = Permission.objects.filter(
        codename__in=[
            'add_maintenancerecord', 'change_maintenancerecord',
            'delete_maintenancerecord', 'view_maintenancerecord',
            'view_car',
        ]
    )
    mechanic_group.permissions.set(mechanic_permissions)


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Garage Owner', 'Mechanic']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]