# Generated by Django 6.0.1 on 2026-02-04 13:39

import maintenance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[maintenance.validators.validate_maintenance_cost]),
        ),
    ]
